# Generated by Django 4.2.4 on 2025-06-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='served_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('finished', 'Finished'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderfeaturedetail',
            name='order_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='orders.orderdetail'),
        ),
    ]
