# Generated by Django 4.2.4 on 2025-06-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_worker_id_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
